[project]
name = "app_master"
version = "0.1.0"
description = "app_master using crewAI"
authors = [{ name = "Agustin C", email = "agustin.compeanc@gmail.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.159.0,<1.0.0",
    "langchain-google-genai>=2.1.9",
    "scrapfly-sdk>=0.8.23",
    "selenium>=4.35.0",
    "spider-client>=0.1.72",
    "webdriver-manager>=4.0.2",
]

[project.scripts]
app_master = "app_master.main:run"
run_crew = "app_master.main:run"
train = "app_master.main:train"
replay = "app_master.main:replay"
test = "app_master.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
